import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';
import { MQTTcollection } from '/lib/collections/collections.js';

SimpleSchema.extendOptions(['autoform']);

export const Branches = new Mongo.Collection('branches');

Branches.allow({
    insert: function(){
        return true;
    },
    update: function(){
        return true;
    },
    remove: function(){
        return true;
    }
});


BranchesSchema = new SimpleSchema({
  name: {
      type: String,
      label: 'Branch Name',
      optional: false,
  },
  details: {
      type: String,
      label: 'Details',
      optional: true,
      autoform: {
         type: 'textarea'
      }
  },
  author: {
    type: String,
    label: "Generated by",
    autoValue: function(){
        return this.userId;
    },
    autoform:{
        type: "hidden",
    }
  },
  createdAt:{
      type: Date,
      label: "Created at ",
      autoValue: function(){
        return new Date();
      },
      autoform:{
          type: "hidden",
      }

  },
  dontShowThis: {
      type: Boolean,
      optional: true,
      label: "Delete",
      autoform:{
          type: "hidden",
      },
      defaultValue: false,
  }
} , { tracker: Tracker });

var BranchesSchemaContext = BranchesSchema.newContext("pollingItem");
BranchesSchema.validator();

Branches.attachSchema(BranchesSchema);

if (Meteor.isClient) {
    Meteor.subscribe('branches');

}

if (Meteor.isServer) {
    Meteor.methods({
            removeTopicsBranch: function(id){
                console.log(id);
                MQTTcollection.remove({"topic" : {$regex : ".*"+id+".*"}});
                Branches.update({_id:id},{$set:{dontShowThis:true}});
            },
            reMapElementBranch: function(id,position,mapnum){
                console.log(id);
                console.log(position);
                if(mapnum==null){
                  mapnum="1";
                }
                Branches.update({_id:id},{$set:{mapx:position.mapx, mapy:position.mapy,mapnum:mapnum}});
            },
            removeMapElementBranch: function(id){
                console.log(id);
                Branches.update({_id:id},{$set:{mapnum:"0"}});
            },
    });

}
